### ISSUE TITLE
pytest error - please see body context

### ISSUE THREAD

**Issue by minkyu-choi07** [UTAustin-SwarmLab/Swarm-Visualization#12]
___________________________ ERROR collecting tests/test_p_value.py ___________________________
ImportError while importing test module '/Users/minkyuchoi/repos/SwarmLab/Swarm-Visualization/tests/test_p_value.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.asdf/installs/python/3.8.16/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_p_value.py:12: in <module>
    from swarm_visualizer.utility.statistics_utils import add_wilcoxon_value
swarm_visualizer/utility/statistics_utils.py:1: in <module>
    from statannot import add_stat_annotation
E   ModuleNotFoundError: No module named 'statannot'

**Comment by d31003** [comment]
I think that is added by OA in the newest pull request
