### ISSUE TITLE
set_plot_properties auto layout

### ISSUE THREAD

**Issue by minkyu-choi07** [UTAustin-SwarmLab/Swarm-Visualization#15]
set_plot_properties()
ln 18.

Let's parameterize "figure.autolayout": True

Example:
def set_plot_properties(
    font_size: float = 20,
    legend_font_size: float = 14,
    xtick_label_size: float = 14,
    ytick_label_size: float = 14,
    markersize: float = 10,
    usetex: bool = True,
    autolayout = True,
) -> None:

**Comment by d31003** [comment]
Fixed in the latest commit.
